name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # 1) Code auschecken
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2) Node.js einrichten (Corepack ist inklusive)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3) Corepack aktivieren & pnpm vorbereiten
      - name: Enable Corepack & pnpm
        run: |
          corepack enable
          corepack prepare pnpm@10.10.0 --activate

      # 4) pnpm-Store cache (optional, aber beschleunigt Builds)
      - name: Cache pnpm store
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      # 5) Dependencies installieren
      - name: Install dependencies
        run: pnpm install

      # 6) Build erzeugen
      - name: Build production bundle
        run: pnpm run build

      # 7) Deploy auf gh-pages-Branch
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
